CREATE SEQUENCE SEQ_CARBONO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_INICIATIVA_REDUCAO_CARBONO (
    REDUCAO_CARBONO_ID INTEGER DEFAULT SEQ_CARBONO.NEXTVAL NOT NULL,
    DESCRICAO                     VARCHAR2(200) NOT NULL,
    CATEGORIA                     VARCHAR2(100) NOT NULL,
    STATUS                        VARCHAR2(30) NOT NULL,
    EMISSAO_BASE_TCO2E            NUMBER(15,2) NOT NULL,
    META_REDUCAO_TCO2E            NUMBER(15,2) NOT NULL
);